[openai]
openai_url = "https://api.openai.com/v1"

[openrouter]
openai_url = "https://openrouter.ai/api/v1"
anthropic_url = "https://openrouter.ai/api"

[deepseek]
openai_url = "https://api.deepseek.com"

[groq]
openai_url = "https://api.groq.com/openai/v1"

[together]
openai_url = "https://api.together.xyz/v1"

[mistral]
openai_url = "https://api.mistral.ai/v1"

[perplexity]
openai_url = "https://api.perplexity.ai"

[gemini]
openai_url = "https://generativelanguage.googleapis.com/v1beta/openai/"

[x-ai]
openai_url = "https://api.x.ai/v1"

[zai]
openai_url = "https://api.z.ai/api/paas/v4/"
anthropic_url = "https://api.z.ai/api/anthropic"

[ollama]
openai_url = "http://localhost:11434/v1"
anthropic_url = "http://localhost:11434"
